[14-04-19 00:08:51][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/menqiao_weixin/proj1/etc/includes_dev.json)
[14-04-19 00:10:26][MainThread][route.py:75] WARNING: method refuse!uri=json,method=1,parameters=||
[14-04-19 00:10:33][MainThread][route.py:92] INFO: json {}
[14-04-19 00:10:44][MainThread][route.py:92] INFO: json {}
[14-04-19 00:10:58][MainThread][route.py:92] INFO: json {u'who': u'bill'}
[14-04-19 00:11:56][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/menqiao_weixin/proj1/etc/includes_dev.json)
[14-04-19 00:11:59][MainThread][route.py:92] INFO: json {}
[14-04-19 00:12:08][MainThread][route.py:92] INFO: json {'who': 'bbbbb'}
[14-04-19 08:32:42][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/iceworld/multithreadtornado/etc/includes_dev.json)
[14-04-19 08:32:44][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:32:44][Thread-1][route.py:23] ERROR: error
Traceback (most recent call last):
  File "/home/rowland/myGit/iceworld/multithreadtornado/lib/util/route.py", line 21, in _call_wrap
    ret = call(*params)
  File "/home/rowland/myGit/iceworld/multithreadtornado/biz/hello.py", line 37, in test5
    return self.cache1()
  File "/home/rowland/myGit/iceworld/multithreadtornado/lib/util/cache.py", line 97, in deco_args
    ret = func(*argv,**kwargv)
  File "/home/rowland/myGit/iceworld/multithreadtornado/biz/hello.py", line 53, in cache1
    raise e
AttributeError: 'module' object has no attribute 'openurl'
[14-04-19 08:33:08][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/iceworld/multithreadtornado/etc/includes_dev.json)
[14-04-19 08:33:10][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:33:10][Thread-1][route.py:23] ERROR: error
Traceback (most recent call last):
  File "/home/rowland/myGit/iceworld/multithreadtornado/lib/util/route.py", line 21, in _call_wrap
    ret = call(*params)
  File "/home/rowland/myGit/iceworld/multithreadtornado/biz/hello.py", line 37, in test5
    return self.cache1()
  File "/home/rowland/myGit/iceworld/multithreadtornado/lib/util/cache.py", line 97, in deco_args
    ret = func(*argv,**kwargv)
  File "/home/rowland/myGit/iceworld/multithreadtornado/biz/hello.py", line 53, in cache1
    raise e
ValueError: unknown url type: news.baidu.com
[14-04-19 08:33:27][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/iceworld/multithreadtornado/etc/includes_dev.json)
[14-04-19 08:33:27][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:34:10][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/iceworld/multithreadtornado/etc/includes_dev.json)
[14-04-19 08:34:11][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:35:43][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/iceworld/multithreadtornado/etc/includes_dev.json)
[14-04-19 08:35:45][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:35:48][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:35:49][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:36:19][MainThread][serv.py:117] INFO: starting..., listen [8888], configurated by (/home/rowland/myGit/iceworld/multithreadtornado/etc/includes_dev.json)
[14-04-19 08:36:22][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:36:24][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:36:25][MainThread][route.py:92] INFO: test/cache {}
[14-04-19 08:36:27][MainThread][route.py:92] INFO: test/cache {}
